name: Deploy to AWS S3 + CloudFront

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

env:
  AWS_REGION: ap-northeast-1
  S3_BUCKET: pockercashflow-1750603012.85526
  CLOUDFRONT_DISTRIBUTION_ID: E3GUYCNLRRQECZ
  CLOUDFRONT_DOMAIN: d1vp9iofpvfkkg.cloudfront.net

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Build application
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}

      - name: Deploy to S3
        run: |
          # Upload static assets with long cache
          aws s3 sync dist/ s3://${{ env.S3_BUCKET }}/ \
            --delete \
            --cache-control "max-age=31536000" \
            --exclude "index.html" \
            --exclude "*.html"

          # Upload HTML files with no cache (for SPA routing)
          aws s3 sync dist/ s3://${{ env.S3_BUCKET }}/ \
            --delete \
            --cache-control "no-cache" \
            --include "*.html"

      - name: Invalidate CloudFront cache
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ env.CLOUDFRONT_DISTRIBUTION_ID }} \
            --paths "/*"

      - name: Deployment success notification
        run: |
          echo "🎉 Deployment completed successfully!"
          echo "🌍 Your app is live at: https://${{ env.CLOUDFRONT_DOMAIN }}"
